### ISSUE TITLE
Multiple insertions

### ISSUE THREAD

**Issue by alephreish** [maryamrabiee/INSTRAL#3]
It seems that `multiple_placements.sh` is not functional, because the script `combine_insertions.py` that is supposed to actually do the job is not there.

Also, I personally think that `multiple_placements.sh` suffers from several easily fixable drawbacks that render its use unsafe and prone to cause unnecessary complications to the user, like the requirement to provide instral path, intolerance to white space in paths, dependency on newick utilities, hard-coded instral version, lack of shebang and requirement for the working directory to contain (a link to) `combine_insertions.py` (instead of taking it from the instral directory). I'm ready to volunteer a PR once `combine_insertions.py` is added.

An unrelated question: Is there a plan to implement ordered placement?

**Comment by maryamrabiee** [comment]
Thank you for your comments. I have uploaded the `combine_insertions.py` file and will update the old script soon.

Regarding your other question, I should say, no, there is no plan to implement ordered placement. However, it is super easy to be done with INSTRAL.

**Comment by alephreish** [comment]
Great, thanks! A PR for `multiple_placements.sh` is on me.

>However, it is super easy to be done with INSTRAL.

Yes, a simple loop, I agree
